const qplLibraries = [
    'Arverne',
    'Astoria',
    'Auburndale',
    'Baisley Park',
    'Bay Terrace',
    'Bayside',
    'Bellerose',
    'Briarwood',
    'Broad Channel',
    'Broadway',
    'Cambria Heights',
    'Central Library',
    'Corona',
    'Court Square',
    'Douglaston/Little Neck',
    'East Elmhurst',
    'East Flushing',
    'Elmhurst',
    'Far Rockaway',
    'Flushing',
    'Forest Hills',
    'Fresh Meadows',
    'Glen Oaks',
    'Glendale',
    'Hillcrest',
    'Hollis',
    'Howard Beach',
    'Hunters Point',
    'Jackson Heights',
    'Kew Gardens Hills',
    'Langston Hughes',
    'Laurelton',
    'Lefferts',
    'Lefrak City',
    'Long Island City',
    'Maspeth',
    'McGoldrick',
    'Middle Village',
    'Mitchell-Linden',
    'North Forest Park',
    'North Hills',
    'Ozone Park',
    'Peninsula',
    'Pomonok',
    'Poppenhusen',
    'Queens Village',
    'Queensboro Hill',
    'Rego Park',
    'Richmond Hill',
    'Ridgewood',
    'Rochdale Village',
    'Rosedale',
    'Seaside',
    'South Hollis',
    'South Jamaica',
    'South Ozone Park',
    'St. Albans',
    'Steinway',
    'Sunnyside',
    'Whitestone',
    'Windsor Park',
    'Woodhaven',
    'Woodside'
]